### ISSUE TITLE
Criar módulo de SMC

### ISSUE THREAD

**Issue by AlyssonG** [fjmendes1994/george-compiler#6]

**Comment by fjmendes1994** [comment]
Alysson, acho que é melhor criar um smc_test para colocar os testes referentes ao SMC

**Comment by phelipegm** [comment]
Boa noite, criei o smc_test.

**Comment by fjmendes1994** [comment]
Boa noite Phelipe, procure só implementar o que é referente a issue que você ta como assigned. Nesse caso que o Alysson está designado para esta issue, você criando esse modulo vai gerar merge conflicts quando o Alysson for passar o que ele fez para a brach development sem contar que os testes que você colocou la não são mais validos.
